### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by heikoch** [BigJBehr/ESP32-Bluetooth-BLE-Remote-Control#1]
I get the following error messages when compiling ...

```
"/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++" -DESP_PLATFORM -DMBEDTLS_CONFIG_FILE="mbedtls/esp_config.h" -DHAVE_CONFIG_H "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/config" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/bluedroid" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/app_trace" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/app_update" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/bootloader_support" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/bt" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/driver" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/esp32" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/esp_adc_cal" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/ethernet" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/fatfs" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/freertos" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/heap" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/jsmn" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/log" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/mdns" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/mbedtls" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/mbedtls_port" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/newlib" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/nvs_flash" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/openssl" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/spi_flash" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/sdmmc" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/spiffs" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/tcpip_adapter" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/ulp" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/vfs" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/wear_levelling" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/xtensa-debug-module" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/coap" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/console" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/expat" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/json" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/lwip" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/newlib" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/nghttp" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/soc" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/tools/sdk/include/wpa_supplicant" -std=gnu++11 -fno-exceptions -Os -g3 -Wpointer-arith -fexceptions -fstack-protector -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -mlongcalls -nostdlib -w -Wno-error=unused-function -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-sign-compare -fno-rtti -MMD -c -DF_CPU=240000000L -DARDUINO=10805 -DARDUINO_LOLIN32 -DARDUINO_ARCH_ESP32 -DARDUINO_BOARD="LOLIN32" -DARDUINO_VARIANT="lolin32"  -DESP32 -DCORE_DEBUG_LEVEL=0 "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/cores/esp32" "-I/home/heikoch/bin/arduino-1.8.5/hardware/espressif/esp32/variants/lolin32" "/tmp/arduino_build_568207/sketch/Gatt-VRBOX-Tasks.ino.cpp" -o "/tmp/arduino_build_568207/sketch/Gatt-VRBOX-Tasks.ino.cpp.o"
/home/heikoch/Arduino/ESP32-Bluetooth-BLE-Remote-Control/Gatt-VRBOX-Tasks/Gatt-VRBOX-Tasks.ino: In function 'void gattc_profile_event_handler(esp_gattc_cb_event_t, esp_gatt_if_t, esp_ble_gattc_cb_param_t*, int)':
Gatt-VRBOX-Tasks:415: error: cannot convert 'bool' to 'esp_ble_addr_type_t' for argument '3' to 'esp_err_t esp_ble_gattc_open(esp_gatt_if_t, uint8_t*, esp_ble_addr_type_t, bool)'
         esp_ble_gattc_open(profiles[BATTERY_PROFILE].gattc_if, profiles[BATTERY_PROFILE].remote_bda, true);
                                                                                                          ^
/home/heikoch/Arduino/ESP32-Bluetooth-BLE-Remote-Control/Gatt-VRBOX-Tasks/Gatt-VRBOX-Tasks.ino: In function 'void esp_gap_cb(esp_gap_ble_cb_event_t, esp_ble_gap_cb_param_t*)':
Gatt-VRBOX-Tasks:582: error: cannot convert 'bool' to 'esp_ble_addr_type_t' for argument '3' to 'esp_err_t esp_ble_gattc_open(esp_gatt_if_t, uint8_t*, esp_ble_addr_type_t, bool)'
                 esp_ble_gattc_open(profiles[HID_PROFILE].gattc_if, scan_result->scan_rst.bda, true);
                                                                                                   ^
exit status 1
cannot convert 'bool' to 'esp_ble_addr_type_t' for argument '3' to 'esp_err_t esp_ble_gattc_open(esp_gatt_if_t, uint8_t*, esp_ble_addr_type_t, bool)'
```
Does somebody has any idea?
Thanks Heiko

**Comment by niwalz** [comment]
Same problem here..  anybody solved this?

**Comment by BigJBehr** [comment]
The issue has too parts. The first part is that sometime during development of this code, a new version of the ESP32 Arduino SDK was released. The new version is not backward compatible with the version that I used. For example, one of the Bluetooth functions changed from three parameters to four parameters. That is why you are getting the compilation error. I have fixed that issue, but have not released new code. The reason I have not released new code is that Expressif broke something in the Bluetooth stack that causes it to crash when run. Bottom line, I have code that will compile, but crashes when run.
If you can find the previous release of the Arduino SDK and compile with it then the code will run flawlessly.

**Comment by BigJBehr** [comment]
I have a version of this project that was written to use Neil Kolban's class based implementaion of the Bluetooth interface. This works to a point. The joystick and trigger buttons are functional. However, the other four buttons are not functional. The explanation for why that is is complicated. Mr Kolban and his team are looking into the issue. If you can live with just the joystick and trigger buttons then contact me and I will send you a zip file with the code.

**Comment by niwalz** [comment]
Perfect I still need the Code for the Joystick. 
Can you send it to my email adress? I ve written you an email.

**Comment by ludo-d** [comment]
Hi BigBehr
I 'm also verry interested in you Niel Kolban's class based implementation (joystick + Trigger buttons is enough for me)
can you send me the code too please

**Comment by niwalz** [comment]
Hi Ludo,

 

i got this Codes with a few problems have a year ago.

I made it working for me with the most BLE (!) - Controllers.

If you want the Arduino Code for the ESP32 i could send it

 

Nico

 

Gesendet: Montag, 15. April 2019 um 11:55 Uhr
Von: "Ludo D" <notifications@github.com>
An: BigJBehr/ESP32-Bluetooth-BLE-Remote-Control <ESP32-Bluetooth-BLE-Remote-Control@noreply.github.com>
Cc: niwalz <nicowalz95@web.de>, Comment <comment@noreply.github.com>
Betreff: Re: [BigJBehr/ESP32-Bluetooth-BLE-Remote-Control] Compiling error (#1)


Hi BigBehr
I 'm also verry interested in you Niel Kolban's class based implementation (joystick + Trigger buttons is enough for me)
can you send me the code too please

**Comment by ludo-d** [comment]
Hi Nico
I would like it a lot if you could send me the code for esp32 please.
Arduino or espressif, both are ok

Thanks in advance
Regards
Ludo


Op ma 15 apr. 2019 12:57 schreef niwalz <notifications@github.com>:

**Comment by niwalz** [comment]
Hi,

 

i attached the file i have at home. I am next on 26.4 at work, so if it is not working for you, let me know.

Then i ll send you the actual one from work. I am not sure if this is the correct file. Haven't worked with it since November.

 

BTW: Sorry for my bad english.. hope you understand everything, i am from Germany.

 

Where are you from?

 

Regards

Nico

 

Gesendet: Montag, 15. April 2019 um 13:25 Uhr
Von: "Ludo D" <notifications@github.com>
An: BigJBehr/ESP32-Bluetooth-BLE-Remote-Control <ESP32-Bluetooth-BLE-Remote-Control@noreply.github.com>
Cc: niwalz <nicowalz95@web.de>, Comment <comment@noreply.github.com>
Betreff: Re: [BigJBehr/ESP32-Bluetooth-BLE-Remote-Control] Compiling error (#1)

Hi Nico
I would like it a lot if you could send me the code for esp32 please.
Arduino or espressif, both are ok

Thanks in advance
Regards
Ludo


Op ma 15 apr. 2019 12:57 schreef niwalz <notifications@github.com>:

**Comment by ludo-d** [comment]
Hi Nico,
Maybe I 'm mistaken, but I don't find any attachment here maybe it removed
by security policies from Google (zip files are removed).
maybe you can try my other mail adress: ludo.dreesen@skynet.be

BTW your English is probably better then mine:) (from Belgium)


regards
Ludo

Op di 16 apr. 2019 om 12:10 schreef niwalz <notifications@github.com>:

**Comment by DerfJagged** [comment]
@niwalz @ludo-d 
Do either of you still have the code for the joystick controls? I would love to use it.

**Comment by ludo-d** [comment]
[Boccia.zip](https://github.com/BigJBehr/ESP32-Bluetooth-BLE-Remote-Control/files/3963979/Boccia.zip)

this is an adapted version to be used for a Boccia ramp (for disabled people)
Hope it can be of any use to you.

regards
Ludo

**Comment by ludo-d** [comment]
PS: Make sure that the controller used is a BLE4.0 or higher version, 3.0 will not work
I used this one:https://www.grandado.com/products/draadloze-bluetooth-4-0-mini-ring-oplaadbare-draadloze-vr-remote-game-controller-joystick-gamepad-voor-android-3d-bril
